export const vegetables = [
    {
        color: 'red',
        name: 'radish',
        price: 2,
        isCrunchy: true,
        img: 'http://www.placekitten.com/200/200',
        status: 'fresh',
    },
    {
        color: 'green',
        name: 'pepper',
        onSale: true,
        availableOnDate: 1459435092834,
        endDate: 2345045820098,
        price: 1,
        isCrunchy: true,
        img: 'http://www.placekitten.com/200/200',
        status: 'fresh',
    },
    {
        color: 'green',
        name: 'broccolini',
        price: 3,
        isCrunchy: true,
        img: 'http://www.placekitten.com/200/200',
        status: 'frozen',
    }, 
    {
        color: 'green',
        name: 'green beans',
        price: 2,
        isCrunchy: false,
        img: 'http://www.placekitten.com/200/200',
        status: 'canned',
    },
    {
        color: 'orange',
        name: 'carrots',
        price: 2,
        isCrunchy: false,
        img: 'http://www.placekitten.com/200/200',
        status: 'frozen',
    }, 
    {
        color: 'yellow',
        name: 'corn',
        onSale: true,
        price: 1,
        isCrunchy: true,
        img: 'http://www.placekitten.com/200/200',
        status: 'canned',
    }, 
    {
        color: 'orange',
        name: 'pumpkin',
        price: 4,
        isCrunchy: false,
        img: 'http://www.placekitten.com/200/200',
        status: 'fresh',
    }, 
    {
        color: 'red',
        name: 'red pepper',
        price: 2,
        isCrunchy: true,
        img: 'http://www.placekitten.com/200/200',
        status: 'fresh',
    },
];